services:
	mongodb:
		image:mongo
		container_name:mongo_db
		ports:
			- 27017:27017
		volumes:
			- mongo:/data
		environment:
			- MONGO_INTIDB_ROOT_USERNAME=mohit
			- MONGO_INTIDB_ROOT_PASSWORD=mohit
	mongo-expresss:
		image: mongo-express
		container_name: mongo_express
		restart: always
		ports:
			- 8081:8081
		environment:
			- ME_CONFIG_MONGODB_ADMINUSERNAME=mohit
			- ME_CONFIG_MONGODB_ADMINPASSWORD=mohit
			- ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
	mongo:{}
			